name: "ESLint Annotate from Report JSON"
description: "Annotates pull request diffs with warnings and errors from an ESLint report JSON file."
inputs:
  repo-token:
    description: "Token used to interact with the Github API."
    required: true
  report-json:
    description: "ESLint report file in JSON format."
    default: "eslint_report.json"
    required: false
  only-pr-files:
    description: "Only annotate files changed when run on pull requests"
    default: 'true'
    required: false
  fail-on-warning:
    description: "Fail the GitHub Action when ESLint warnings are detected. Set to 'true' to enable."
    default: 'false'
    required: false
  check-name:
    description: "The name of the GitHub status check created."
    default: 'ESLint Report Analysis'
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "check-circle"
  color: "yellow"
