import {ESLintReport} from '../types'

/* eslint-disable */

const reportJSExpected: ESLintReport = [{suppressedMessages: [], fatalErrorCount: 0, "filePath":`src/__tests__/eslintJsonReportToJs.test.ts`,"messages":[{"ruleId":"prettier/prettier","severity":2,"message":"Delete `;`","line":20,"column":6,"endLine":20,"endColumn":7,"fix":{"range":[609,610],"text":""}},{"ruleId":"prettier/prettier","severity":2,"message":"Delete `;`","line":21,"column":52,"endLine":21,"endColumn":53,"fix":{"range":[662,663],"text":""}},{"ruleId":"prettier/prettier","severity":2,"message":"Insert `⏎`","line":25,"column":3,"endLine":25,"endColumn":3,"fix":{"range":[809,809],"text":"\n"}}],"errorCount":3,"warningCount":0,"fixableErrorCount":3,"fixableWarningCount":0,"source":"import eslintJsonReportToJs from '../eslintJsonReportToJs'\n\ndescribe('ESLint report JSON to JS', () => {\n  it('converts an ESLint JSON file to a JS object', async () => {\n    const reportJSExpected = [\n      '.vscode/settings.json',\n      'action.yml',\n      'dist/index.js',\n      'jest.config.js',\n      'package-lock.json',\n      'package.json',\n      'src/analyze-eslint-js.ts',\n      'src/constants.ts',\n      'src/eslint-action.ts',\n      'src/eslint-json-report-to-js.ts',\n      'src/get-pr-files-changed.ts',\n      'src/split-array-into-chunks.ts',\n      'src/types.d.ts',\n      'tsconfig.json',\n    ];\n    const reportJS = await eslintJsonReportToJs('');\n    // https://jestjs.io/docs/en/expect#expectarraycontainingarray\n    expect(reportJS).toEqual(expect.arrayContaining(reportJSExpected))\n  })\n})","usedDeprecatedRules":[]},{suppressedMessages: [], fatalErrorCount: 0, "filePath":`src/__tests__/getPullRequestFiles.test.ts`,"messages":[],"errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]},{suppressedMessages: [], fatalErrorCount: 0, "filePath":`src/constants.ts`,"messages":[],"errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]},{suppressedMessages: [], fatalErrorCount: 0, "filePath":`src/eslintJsonReportToJs.ts`,"messages":[],"errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]},{suppressedMessages: [], fatalErrorCount: 0, "filePath":`src/getPullRequestFiles.ts`,"messages":[],"errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]},{suppressedMessages: [], fatalErrorCount: 0, "filePath":`src/index.ts`,"messages":[],"errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]},{suppressedMessages: [], fatalErrorCount: 0, "filePath":`src/types.d.ts`,"messages":[],"errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]}]

/* eslint-enable */

export default reportJSExpected
